name: release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 15.x

      - name: Fetch GHPages repo
        run: |
          echo "GET IN MAH BELLEH"
          pwd
          git clone https://github.com/mdanlowski/mdanlowski.github.io.git ~/mdanlowski.github.io
          ls -la

      # Runs a single command using the runners shell
      - name: Build the project
        run: npm run build

      # Runs a set of commands using the runners shell
      - name: TODO - Commit built files to the GHPages repo
        run: |
          echo "where am ayyy?"
          pwd
