name: release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 12.0.0

      - name: Fetch GHPages repo
        run: |
          echo "GET IN MAH BELLEH"
          git clone https://github.com/mdanlowski/mdanlowski.github.io.git ../mdanlowski.github.io

      # Runs a single command using the runners shell
      - name: Build the project
        run: |
          npm install
          npm run build
          
      - name: Commit built files to the GHPages repo
        run: |
          ls -la ../
          rm -rf ../mdanlowski.github.io/js ../mdanlowski.github.io/css ../mdanlowski.github.io/img

      # Runs a set of commands using the runners shell
      - name: Commit built files to the GHPages repo
        run: |
          rm -rf ../mdanlowski.github.io/js ../mdanlowski.github.io/css ../mdanlowski.github.io/img
          cp -R ./dist/ ../mdanlowski.github.io/
          git -C "../mdanlowski.github.io" status
          git -C "../mdanlowski.github.io" add .
          git -C "../mdanlowski.github.io" commit -am "Portfolio built with GHActions, v. $(date)"
          git -C "../mdanlowski.github.io" push origin master
      
      # Ping me when ready
      #- name: Some sort of notification here
      #  run: 
